*** Settings ***

*** Variables ***

&{produto}
...    id=B0D54R28GX
...    nome=Blance, Kit Película de Vidro + Caneta Touch Para Tablet Vaio TL10
...    preco=59.90
...    url=https://www.amazon.com.br/gp/product/B0D54R28GX/ref=sw_img_1?smid=A2APB4UR2CM3JH
...    imagem_principal=https://m.media-amazon.com/images/I/51imWeXES0L._AC_AA152_.jpg

&{produto_sem_estoque}
...    id=B0CKD6LZ16
...    nome=Smartphone Samsung Galaxy S24, Galaxy AI, Selfie de 12MP, Tela de 6.2" 1-120Hz, 128GB, 8GB RAM - Creme
...    url=https://www.amazon.com.br/Smartphone-Samsung-Galaxy-Selfie-1-120Hz/dp/B0CRRVBQ9W/ref=sr_1_3?__mk_pt_BR=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=UZSDIDBSBYLQ&dib=eyJ2IjoiMSJ9.6f4TsyYBibFRJ97CvMvuHsy2MdmJ55XJzFdkh4t7NehxNsWL0m23gn-diZ2NPRoxYkGs_CKw3LxK-Lak8Jop2IYmLuSsYWTutlwm1J1IzyO3buzlhC2QxYc7LoR4KmVadH6oJlpVXqkvTtilu5IupKRS38_KswRq5mjqaHrjldJOVqv-LKKnlI0UUgbwsboRQIdmlD7gjCq5T2Jt4uvZmuFCF-zBzCsgYYNi-vF7_n8xQHg4q3YIfnPe9cIMZgZSpw4LuiMWTh8jcC6Qi0-3YSdySiGyfqmU-nXpGJig8JfBNrU0RllCBccZ1-LqNHjBtXkbhJU5tt0lXJ8xINimo_g_fi718vofH3kgDN4qmWR5zysJMA5IYBTcxpxcavAq3eQJjUy3MUyLX3ZU69qHtkaPTR7oa1Ahco6yehTIw4O4hFR2KAfNBFf7UGXSn4gF.DJ3Txpz0YrvwnMeGuSPPMrkTz6e9yl8ZgvmJmi8XKlE&dib_tag=se&keywords=s24&qid=1741452967&sprefix=s2%2Caps%2C204&sr=8-3&ufe=app_do%3Aamzn1.fos.95de73c3-5dda-43a7-bd1f-63af03b14751&th=1
